Add I2C manipulation module for platform Simplelink
contiki-ng/contiki-ng pull request #1285
Opened 2020-05-30 18:00 UTC by g-oikonomou

All Simplelink sensortag sensing element drivers implement I2C transactions and bus manipulation internally using static functions. This creates a lot of code duplication.

This work in progress makes moves all those functions to a new module and makes them re-usable. It also changes all affected drivers to use those new functions.

This will be very handy once we have finalised our I2C HAL (#1242), since the new module implemented here is where we'd put all of the HAL's arch-specific functions.

Requires #1283

2020-10-19 00:41 UTC, alexstanoev requested changes

2020-10-19 00:41 UTC, alexstanoev commented on arch/cpu/simplelink-cc13xx-cc26xx/dev/i2c-arch.c
> +  if(i2c_handle) {
Should be `if(!i2c_handle) {`

2020-10-19 00:41 UTC, alexstanoev commented on arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c
> +  if(i2c_handle) {
Should be `if(!i2c_handle) {`

2020-11-23 21:33 UTC, g-oikonomou commented
Rebased on top of `develop`

2020-11-23 21:33 UTC, g-oikonomou commented on arch/platform/simplelink/cc13xx-cc26xx/sensortag/tmp-007-sensor.c
> +  if(i2c_handle) {
Fixed by rebase

2020-11-23 21:33 UTC, g-oikonomou commented on arch/cpu/simplelink-cc13xx-cc26xx/dev/i2c-arch.c
> +  if(i2c_handle) {
Fixed with new commit

2020-11-25 18:59 UTC, alexstanoev approved these changes

2020-11-25 19:14 UTC, merged