Bugfix/snmp engine
contiki-ng/contiki-ng pull request #1355
Opened 2020-08-17 21:04 UTC by mjurczak

Initial work to fix most critical issues described in SNMP agent implementation:
https://github.com/contiki-ng/contiki-ng/issues/1354
https://github.com/contiki-ng/contiki-ng/issues/1353
https://github.com/contiki-ng/contiki-ng/issues/1352
https://github.com/contiki-ng/contiki-ng/issues/1351

The proposed changes require testing and do not cover all out-of-bounds conditions that may occur when processing incoming SNMP requests. 

I think it would also be great if there was an automated method of functional validation of the SNMP agent implementation.

2020-08-19 18:00 UTC, Yagoor commented
Hi mjurczak,
I implemented the SNMP protocol last year.

I believe you have some tests scenarios that you used to catch these bugs.
Could you add them to the unit test?
The unit test basically only validates the protocol, meaning that it makes sure it is compliant, but it doesn't really stresses it.

2020-08-20 18:52 UTC, mjurczak commented
Hi Yagoor,

Some sample inputs are provided in issue describtions. I will provide you with more samples that cause similar porcessing issues.

I will also try to figure out which issues can be verified by UTs. For instance - if the number of requested OIDs exceeds supported value, the parser should be expected to return an error I think.
On the other hand, writes and reads beyond buffer boundaries and certain class of stack overwrite issues may either pass unnoticed in UTs or cause UT framework crash.

Most of the described issues were discovered by means of fuzzing. It would be my pleasure to post a sample base app and a short description on how to run fuzzer on the SNMP agent.

Kind regards.

2020-09-08 17:22 UTC, Yagoor approved these changes
Hi @g-oikonomou.
I took I look into his changes and they all seems pretty neat.

However in order to prevent these issues and making sure they remain fixed I suggest adding the test cases described in the issues he linked to this PR.
Unfortunately, I've been pretty busy at work these days. 

@mjurczak, would you be able to create the unit tests? I have an idea on how to do it. 
If you don't have time I believe a good approach would be to merge this PR without the unit tests and create an issue and assign it to me and in the future I'll create the unit tests and maybe others. Having the issue will keep this under my radar and I won't forget it.

2020-09-08 17:27 UTC, g-oikonomou commented
If this is stand-alone and can be merged without further work I can for sure merge this. Thanks for reviewing!

2020-09-15 20:21 UTC, g-oikonomou commented
@mjurczak @Yagoor are we ready here? Can I merge this?

2020-09-19 17:01 UTC, Yagoor commented
HI @g-oikonomou. I'm working on more improvements in the protocol implementation.
After his points, I reviewed the code and notice more vulnerabilities (corner cases).

I see that you added it to version 4.6 milestones. I'll try to get it done for it.
I'm implementing several unit tests in the engine to make sure it is not only compliant with the protocol but that is also handles corner cases.

2020-09-29 20:13 UTC, g-oikonomou requested changes
Hi @mjurczak thank you for this, I finally managed to make some time to review. Looks good to me. Please if you can fix the code style as per the comments, then I am keen to merge this one. Let me know if you have no time and I'll apply the fixes.

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +  {
Style - opening brace in the same line with the if, like so:

`if(*buff_len == 0) {`

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +  {
Ditto

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +  {
Ditto

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +     type != BER_DATA_TYPE_INTEGER) {
You _could_ keep those in the same line, but you don't have to if you cannot be bothered

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +  {
Ditto

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +    type != BER_DATA_TYPE_OCTET_STRING) {
Same line - optional

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +     len > 4) {
Same line - optional

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +     type != expected_type) {
Same line - optional

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-ber.c
> +     len > 4) {
Same line - optional

2020-09-29 20:13 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-message.c
> +    {
Ditto

2020-10-01 12:32 UTC, g-oikonomou commented on os/net/app-layer/snmp/snmp-message.c
> +    {
Also no space between if and opening paren

2020-10-14 18:35 UTC, g-oikonomou approved these changes

2020-10-14 18:35 UTC, merged

2020-10-14 18:37 UTC, g-oikonomou commented
Style errors fixed in #1414 instead of blocking this one