Orchestra non-storing rule update
contiki-ng/contiki-ng pull request #1520
Opened 2021-03-05 17:17 UTC by atiselsts

This PR improve the energy consumption of the non-storing (NS) rule by only adding Tx links in the timeslots that have a corresponding active neighbor. The idea is outlined and discussed here https://github.com/contiki-ng/contiki-ng/issues/889#issuecomment-566695431

There is a corresponding change in the IPv6 DS code: a new pair of callbacks are added: NETSTACK_CONF_DS6_NEIGHBOR_ADDED_CALLBACK and NETSTACK_CONF_DS6_NEIGHBOR_REMOVED_CALLBACK. These callbacks are only defined when Contiki-NG is built with the Orchestra scheduler.

2021-03-07 10:35 UTC, atiselsts commented
For now this is in draft state, as  #1518 should be merged first, and then this one updated.

2021-05-26 20:12 UTC, atiselsts commented
Now that the root rule PR is merged, this one is ready for review!

2022-05-30 09:04 UTC, atiselsts commented
Probably needs a more extensive review, makes sense to postpone this to future versions IMO.

2022-12-12 21:29 UTC, arurke requested changes
Looks good @atiselsts, just one substantial comment/question, rest is mostly code style. I was thinking to do a quick sanity in FIT IoT-lab, but imo these changes are pretty straightforward.

2022-12-19 13:23 UTC, atiselsts commented on os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
> +        timeslot, 0, 0);
The channel offset here should not matter: select_packet() always sets the right channel offset per packet. I will add a comment that explains this.

2022-12-20 23:01 UTC, arurke commented on os/services/orchestra/orchestra-rule-unicast-per-neighbor-rpl-ns.c
> +        timeslot, 0, 0);
Ah, of course, thx for the clarification

2022-12-20 23:01 UTC, arurke commented
:+1: Thanks for the changes and explanation. You want to squash the last commit before I merge?

2022-12-21 17:01 UTC, atiselsts commented
Commit squashed!

2022-12-21 17:21 UTC, arurke approved these changes

2022-12-21 17:25 UTC, merged