Update coap-example-observe-client.c
contiki-ng/contiki-ng pull request #2157
Opened 2022-08-24 16:28 UTC by yolly98

It's a possible solution to the compilation errors

2022-08-24 17:06 UTC, nfi requested changes
Looks good, but two lines (line 145-146) with the old server_ipaddr need to be removed for the example to build. Also, it would also be good if you do not add whitespaces on empty lines.

2022-11-02 13:18 UTC, nvt commented
@yolly98 Could you please let us know if you intend to address @nfi's comments above?

2022-11-02 15:32 UTC, yolly98 commented
I updated the code addressing the above requests

2022-11-05 18:38 UTC, pjonsson commented on examples/coap/coap-example-client/coap-example-observe-client.c
> +toggle_observation(coap_endpoint_t* server_ep)
Can the argument be `const`?

Formatting: the other pointers use the style `type *thing` rather than `type* thing`.

2022-11-05 18:39 UTC, pjonsson commented
If you rebase the PR on top of latest develop, the readthedocs test will pass.

2023-02-02 20:21 UTC, arurke commented
This looks good to me as well, @yolly98 would you be able to address the comment from pjonsson, and rebasing?

2023-02-16 11:01 UTC, closed without merging