mac-sequence: Set destination sequence number (DSN) in mac-sequence.c
contiki-ng/contiki-ng pull request #2305
Opened 2022-11-29 07:23 UTC by kkrentz

The motivation behind this PR is to eliminate duplicate code and to avoid special handling for DSN=0.

2022-12-09 19:40 UTC, arurke commented
@kkrentz In framer-802154.c there was efforts to ensure the sequence number was not zero - which this PR removes. I can't really tell if it was just to check if a new sequence number was needed, or if there is actually some other parts of the mac or lower layers that rely on this behavior. Any thoughts?

2022-12-10 07:32 UTC, kkrentz commented
@arurke That code in `framer-802154.c` was necessary because there was no clear responsibility for setting the destination sequence number (DSN). If DSN=0, `framer-802154.c` took over. This PR makes the MAC driver responsible for setting the DSN, obviating the special handling for DSN=0. Also, in line with IEEE 802.15.4, outgoing frames no longer skip over DSN=0.

2022-12-10 12:55 UTC, arurke requested changes

2022-12-10 12:55 UTC, arurke commented on os/net/mac/mac-sequence.h
> + * brief       Initializes.
* `\brief`
* How about "Initializes the MAC sequence number to a random value"?  Making it clear that calling it twice actually influences the value.

2022-12-10 16:44 UTC, arurke approved these changes

2022-12-10 16:44 UTC, arurke commented
Thanks for the explanation and fixes @kkrentz

2022-12-16 16:30 UTC, nfi approved these changes

2022-12-16 16:31 UTC, merged